/**
 * Parse gcode file header comments to extract slicer metadata.
 * Supports PrusaSlicer, Bambu Studio, Cura, SuperSlicer formats.
 * @param {Buffer} buffer
 * @returns {object}
 */
export function parseGcodeMetadata(buffer) {
  const text = buffer.toString('utf8', 0, Math.min(buffer.length, 8192));
  const lines = text.split('\n').slice(0, 200);

  const meta = {
    slicerName: null,
    slicerVersion: null,
    layerHeight: null,
    estimatedPrintTimeSeconds: null,
    filamentUsedGrams: null,
    bedTemp: null,
    nozzleTemp: null,
  };

  for (const line of lines) {
    if (!line.startsWith(';')) continue;
    const l = line.slice(1).trim().toLowerCase();

    if (!meta.slicerName && l.includes('generated by')) {
      meta.slicerName = line.slice(1).trim().replace(/generated by /i, '').split(' ')[0];
    }
    if (!meta.layerHeight) {
      const lhMatch = l.match(/layer[_ ]height[:\s=]+([0-9.]+)/);
      if (lhMatch) meta.layerHeight = parseFloat(lhMatch[1]);
    }
    if (!meta.estimatedPrintTimeSeconds) {
      const ptMatch = l.match(/estimated printing time[^=]*=\s*(.+)/);
      if (ptMatch) meta.estimatedPrintTimeSeconds = parsePrintTime(ptMatch[1]);
    }
    if (!meta.filamentUsedGrams) {
      const fgMatch = l.match(/filament used \[g\][:\s=]+([0-9.]+)/);
      if (fgMatch) meta.filamentUsedGrams = parseFloat(fgMatch[1]);
    }
    if (!meta.nozzleTemp) {
      const ntMatch = l.match(/nozzle_temperature[:\s=]+([0-9]+)/);
      if (ntMatch) meta.nozzleTemp = parseInt(ntMatch[1]);
    }
    if (!meta.bedTemp) {
      const btMatch = l.match(/bed_temperature[:\s=]+([0-9]+)/);
      if (btMatch) meta.bedTemp = parseInt(btMatch[1]);
    }
  }

  return meta;
}

function parsePrintTime(str) {
  // e.g. "1h 23m 45s" or "2d 1h 5m"
  let seconds = 0;
  const dMatch = str.match(/(\d+)d/);
  const hMatch = str.match(/(\d+)h/);
  const mMatch = str.match(/(\d+)m/);
  const sMatch = str.match(/(\d+)s/);
  if (dMatch) seconds += parseInt(dMatch[1]) * 86400;
  if (hMatch) seconds += parseInt(hMatch[1]) * 3600;
  if (mMatch) seconds += parseInt(mMatch[1]) * 60;
  if (sMatch) seconds += parseInt(sMatch[1]);
  return seconds || null;
}
